/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myJInternalFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author markhyun
 */
public class BanHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyKhachHnag
     */
    public BanHang() {
        initComponents();
    }

    //check loi
    public boolean batLoi() {
        boolean tma = false, tten = false, tsl = false;
        if (txtSoLuong1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng");
            tsl = false;
        } else {
            try {
                int sl = Integer.parseInt(txtSoLuong1.getText());
                tsl = true;
                if (sl < 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng phải trên 0");
                    tsl = false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là số");
                tsl = false;
            }
        }
        if (txtMaKH1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã khách hàng");
            tma = false;
        } else {
            tma = true;
        }
        if (tma == true && tsl == true) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lbSoLuong1 = new javax.swing.JLabel();
        cbbSanPham1 = new javax.swing.JComboBox<>();
        lbTongTien1 = new javax.swing.JLabel();
        txtSoLuong1 = new javax.swing.JTextField();
        btnThemVaoGioHang1 = new javax.swing.JButton();
        lbNhanVienBanHang1 = new javax.swing.JLabel();
        lbTenKH1 = new javax.swing.JLabel();
        txtTenKH1 = new javax.swing.JTextField();
        lbMaKH1 = new javax.swing.JLabel();
        txtMaKH1 = new javax.swing.JTextField();
        cpThanhToan1 = new javax.swing.JScrollPane();
        tbThanhToan1 = new javax.swing.JTable();
        lbDSSP1 = new javax.swing.JLabel();
        btnXoaSP1 = new javax.swing.JButton();
        btnThanhToan1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1333, 750));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bán hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(229, 189, 240));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(168, 168, 233));

        lbSoLuong1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbSoLuong1.setForeground(new java.awt.Color(252, 244, 252));
        lbSoLuong1.setText("Số lượng");

        cbbSanPham1.setEditable(true);
        cbbSanPham1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        cbbSanPham1.setForeground(new java.awt.Color(124, 124, 124));
        cbbSanPham1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPHONE 6 PLUS 32G ĐEN 99%", "IPHONE 6 32G VÀNG LIKE NEW", "IPHONE 7 64G TRẮNG 99%", "IPHONE 7 PLUS HỒNG 128G LƯỚT", "IPHONE 8 PLUS ĐỎ 64G 99%" }));
        cbbSanPham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSanPham1ActionPerformed(evt);
            }
        });

        lbTongTien1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbTongTien1.setForeground(new java.awt.Color(252, 244, 252));
        lbTongTien1.setText("Tổng tiền:................");

        txtSoLuong1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N

        btnThemVaoGioHang1.setBackground(new java.awt.Color(255, 255, 255));
        btnThemVaoGioHang1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnThemVaoGioHang1.setForeground(new java.awt.Color(72, 61, 139));
        btnThemVaoGioHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Shopping_basket_add_Icon_32.png"))); // NOI18N
        btnThemVaoGioHang1.setText("Thêm vào giỏ hàng");
        btnThemVaoGioHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoGioHang1ActionPerformed(evt);
            }
        });

        lbNhanVienBanHang1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbNhanVienBanHang1.setForeground(new java.awt.Color(252, 244, 252));
        lbNhanVienBanHang1.setText("Nhân viên bán hàng:..............");

        lbTenKH1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbTenKH1.setForeground(new java.awt.Color(252, 244, 252));
        lbTenKH1.setText("Tên khách hàng");

        txtTenKH1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtTenKH1.setEnabled(false);

        lbMaKH1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbMaKH1.setForeground(new java.awt.Color(252, 244, 252));
        lbMaKH1.setText("Mã khách hàng");

        txtMaKH1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtMaKH1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMaKH1CaretUpdate(evt);
            }
        });

        tbThanhToan1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        tbThanhToan1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SẢN PHẨM", "TÊN SẢN PHẨM", "SỐ LƯỢNG", "ĐƠN GIÁ", "THÀNH TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbThanhToan1.setFillsViewportHeight(true);
        cpThanhToan1.setViewportView(tbThanhToan1);

        lbDSSP1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbDSSP1.setForeground(new java.awt.Color(252, 244, 252));
        lbDSSP1.setText("Danh sách sản phẩm");

        btnXoaSP1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaSP1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnXoaSP1.setForeground(new java.awt.Color(72, 61, 139));
        btnXoaSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Shopping_basket_prohibit_Icon_32.png"))); // NOI18N
        btnXoaSP1.setText("Xóa sản phẩm");

        btnThanhToan1.setBackground(new java.awt.Color(255, 255, 255));
        btnThanhToan1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnThanhToan1.setForeground(new java.awt.Color(72, 61, 139));
        btnThanhToan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Shopping_basket_accept_Icon_32.png"))); // NOI18N
        btnThanhToan1.setText("Thanh toán");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lbTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaSP1)
                        .addGap(51, 51, 51)
                        .addComponent(btnThanhToan1)
                        .addGap(52, 52, 52))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lbNhanVienBanHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMaKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTenKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbSanPham1, 0, 0, Short.MAX_VALUE)
                                    .addComponent(lbDSSP1))
                                .addGap(191, 191, 191)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSoLuong1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSoLuong1)
                                        .addGap(62, 62, 62)))))
                        .addGap(163, 163, 163)
                        .addComponent(btnThemVaoGioHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cpThanhToan1))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSoLuong1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDSSP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemVaoGioHang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbSanPham1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(txtSoLuong1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(lbNhanVienBanHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lbMaKH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lbTenKH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenKH1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpThanhToan1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbTongTien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThanhToan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaSP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbSanPham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSanPham1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSanPham1ActionPerformed

    private void txtMaKH1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMaKH1CaretUpdate
        // TODO add your handling code here:
        txtTenKH1.setText(txtMaKH1.getText());
    }//GEN-LAST:event_txtMaKH1CaretUpdate

    private void btnThemVaoGioHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoGioHang1ActionPerformed
        // TODO add your handling code here:
        if (this.batLoi() == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        }
    }//GEN-LAST:event_btnThemVaoGioHang1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan1;
    private javax.swing.JButton btnThemVaoGioHang1;
    private javax.swing.JButton btnXoaSP1;
    private javax.swing.JComboBox<String> cbbSanPham1;
    private javax.swing.JScrollPane cpThanhToan1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbDSSP1;
    private javax.swing.JLabel lbMaKH1;
    private javax.swing.JLabel lbNhanVienBanHang1;
    private javax.swing.JLabel lbSoLuong1;
    private javax.swing.JLabel lbTenKH1;
    private javax.swing.JLabel lbTongTien1;
    private javax.swing.JTable tbThanhToan1;
    private javax.swing.JTextField txtMaKH1;
    private javax.swing.JTextField txtSoLuong1;
    private javax.swing.JTextField txtTenKH1;
    // End of variables declaration//GEN-END:variables
}
