/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myJInternalFrame;

import connectionSQL.connectionSQL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import myClass.ClassNguoiDung;

/**
 *
 * @author markhyun
 */
public class DangKy extends javax.swing.JInternalFrame {

    /**
     * Creates new form DangKy
     *
     */
    ArrayList<ClassNguoiDung> lstAccount = new ArrayList<>();
    Connection cn;
    int index = 0;
    
    public DangKy() {
        initComponents();
        cn = connectionSQL.ketnoi("QLIPHONE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnVaoQuanLi = new javax.swing.JButton();
        lbDangKy = new javax.swing.JLabel();
        lbTenDangNhap = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        lbVaiTro = new javax.swing.JLabel();
        lbXacNhan = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        txtXacNhan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        cbbVaiTro = new javax.swing.JComboBox<>();
        btnDangKi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(229, 189, 240));
        kGradientPanel1.setkStartColor(new java.awt.Color(168, 168, 233));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(677, 454));

        btnVaoQuanLi.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnVaoQuanLi.setForeground(new java.awt.Color(72, 61, 139));
        btnVaoQuanLi.setText("Hủy");
        btnVaoQuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaoQuanLiActionPerformed(evt);
            }
        });

        lbDangKy.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        lbDangKy.setForeground(new java.awt.Color(255, 255, 255));
        lbDangKy.setText("Đăng ký");

        lbTenDangNhap.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbTenDangNhap.setForeground(new java.awt.Color(252, 244, 252));
        lbTenDangNhap.setText("Tên đăng nhập:");

        lbMatKhau.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbMatKhau.setForeground(new java.awt.Color(252, 244, 252));
        lbMatKhau.setText("Mật khẩu: ");

        lbVaiTro.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbVaiTro.setForeground(new java.awt.Color(252, 244, 252));
        lbVaiTro.setText("Vai trò:");

        lbXacNhan.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbXacNhan.setForeground(new java.awt.Color(252, 244, 252));
        lbXacNhan.setText("Xác nhận: ");

        lbMaNV.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbMaNV.setForeground(new java.awt.Color(252, 244, 252));
        lbMaNV.setText("Mã nhân viên:  ");

        txtTenDangNhap.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N

        txtXacNhan.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N

        txtMatKhau.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        txtMaNV.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N

        cbbVaiTro.setEditable(true);
        cbbVaiTro.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        cbbVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lí", "Nhân viên", "" }));
        cbbVaiTro.setOpaque(false);

        btnDangKi.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnDangKi.setForeground(new java.awt.Color(72, 61, 139));
        btnDangKi.setText("Đăng kí");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(lbDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbVaiTro)
                                    .addComponent(lbMaNV)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbXacNhan)
                                                    .addComponent(lbMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(lbTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(btnDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNV)
                                            .addComponent(txtMatKhau)
                                            .addComponent(txtXacNhan)
                                            .addComponent(txtTenDangNhap)
                                            .addComponent(cbbVaiTro, 0, 300, Short.MAX_VALUE)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(btnVaoQuanLi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 94, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(65, 65, 65))))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDangKy)
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenDangNhap, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbXacNhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVaiTro))
                .addGap(27, 27, 27)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKi)
                    .addComponent(btnVaoQuanLi))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:[
        if (this.batLoi() == true) {
            PreparedStatement ps = null;
            try {
                ps = cn.prepareStatement("insert into nguoidung values(?,?,?,?)");
                ps.setString(1, txtTenDangNhap.getText());
                ps.setString(2, txtMatKhau.getText());
                ps.setString(3, txtMaNV.getText());
                Boolean vaitro;
                if (cbbVaiTro.getSelectedItem().equals("Quản lí")) {
                    vaitro=true;
                }
                else{
                    vaitro=false;
                }
                ps.setBoolean(4, vaitro);
                
                int ret = ps.executeUpdate();
                if (ret != -1) {
                    JOptionPane.showMessageDialog(this, "Đăng kí thành công");
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    if (cn != null) {
                        cn.close();
                    }
                    if (ps != null) {
                        ps.close();
                    }
                } catch (Exception ex2) {
                    ex2.printStackTrace();
                }
            }
            
        }
        

    }//GEN-LAST:event_btnDangKiActionPerformed

    private void btnVaoQuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaoQuanLiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnVaoQuanLiActionPerformed
    public boolean batLoi() {
        boolean tdn = false, matkhau = false, xacnhan = false, manv = false;
        if (txtTenDangNhap.getText().length() == 0) {
            jLabel1.setText("Bạn chưa nhập tên đăng nhập");
            tdn = false;
        } else {
            jLabel1.setText(null);
            tdn = true;
        }
        if (txtMatKhau.getText().length() == 0) {
            jLabel2.setText("Bạn chưa nhập mật khẩu");
            matkhau = false;
        } else {
            jLabel2.setText(null);
            matkhau = true;
        }
        if ((txtXacNhan.equals(txtMatKhau))) {
            jLabel3.setText("Mật khẩu không khớp");
            xacnhan = false;
        } else {
            xacnhan = true;
            jLabel3.setText(null);
        }
        if (txtMaNV.getText().length() == 0) {
            jLabel4.setText("Bạn chưa nhập mã nhân viên");
            manv = false;
        } else {
            manv = true;
            jLabel4.setText(null);
        }
        if (tdn == true && matkhau == true && xacnhan == true && manv == true) {
            return true;
        } else {
            return false;
        }
    }

//    public void add() {
//        try {
//            String tendn = txtTenDangNhap.getText();
//            String matkhau = txtMatKhau.getText();
//            String xacnhan = txtXacNhan.getText();
//            String manv = txtMaNV.getText();
//
//            String sql = "insert into nguoidung\n" + "values(?,?,?,?)";
//
//            PreparedStatement pstm = cn.prepareStatement(sql);
//            pstm.setString(1, tendn);
//            pstm.setString(2, matkhau);
//            pstm.setString(3, manv);
//            lstAccount.add(new ClassNguoiDung(tendn, matkhau, xacnhan, manv));
//            int row = pstm.executeUpdate();
//            if (row > 0) {
//                JOptionPane.showMessageDialog(this, "Them thanh cong");
//                index = lstAccount.size() - 1;
//
//            } else {
//                JOptionPane.showMessageDialog(this, "Khong them duoc vao");
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Loi add");
//        }
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnVaoQuanLi;
    private javax.swing.JComboBox<String> cbbVaiTro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbDangKy;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTenDangNhap;
    private javax.swing.JLabel lbVaiTro;
    private javax.swing.JLabel lbXacNhan;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtXacNhan;
    // End of variables declaration//GEN-END:variables
}
