/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myJInternalFrame;

import connectionSQL.connectionSQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author markhyun
 */
public class ThongKe extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyKhachHnag
     */
    Connection cnn;
    DefaultTableModel model;

    public ThongKe() {
        connectionSQL kn = new connectionSQL();
        cnn = kn.ketnoi(title);
        initComponents();
        this.thongKe();
    }

    //thỐng kê
    public void thongKe() {
        model = (DefaultTableModel) tbThongKe.getModel();
        model.setRowCount(0);
        String sql = "select CTHOADON.MASP, TENSP, CAUHINH, TRANGTHAI, RIGHT(CONVERT(varchar(20),NGAYBAN,105),7), SUM(THANHTIEN) AS DOANHTHU\n"
                + "FROM SANPHAM JOIN CTHOADON ON SANPHAM.MASP = CTHOADON.MASP\n"
                + "JOIN HOADON ON HOADON.MAHD = CTHOADON.MAHD\n"
                + "GROUP BY CTHOADON.MASP, TENSP, CAUHINH, TRANGTHAI, RIGHT(CONVERT(varchar(20),NGAYBAN,105),7)";
        try {
            Statement stm = cnn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            int index = 0;
            while (rs.next()) {
                index++;
                Vector v = new Vector();
                v.add(index);
                v.add(rs.getString(1));
                v.add(rs.getString(2) + rs.getString(3) + rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));

                model.addRow(v);
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel4 = new keeptoo.KGradientPanel();
        cpThongKe = new javax.swing.JScrollPane();
        tbThongKe = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        kGradientPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống kê", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel4.setkEndColor(new java.awt.Color(229, 189, 240));
        kGradientPanel4.setkGradientFocus(1000);
        kGradientPanel4.setkStartColor(new java.awt.Color(168, 168, 233));

        tbThongKe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "THỜI GIAN( THÁNG / NĂM)", "TỔNG  DOANH THU"
            }
        ));
        tbThongKe.setFillsViewportHeight(true);
        tbThongKe.setRowHeight(30);
        cpThongKe.setViewportView(tbThongKe);

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cpThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cpThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane cpThongKe;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JTable tbThongKe;
    // End of variables declaration//GEN-END:variables
}
