/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainMenu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author markhyun
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    Connection cn;
    boolean vaitro;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            String user = "sa", password = "123";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://DESKTOP-BFNI15L\\SQLEXPRESS:1433;databaseName=QLIPHONE";
            cn = DriverManager.getConnection(url, user, password);
            if (cn != null) {
                System.out.println("Kết nối thành công");
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lbTitle = new javax.swing.JLabel();
        lbTenDangNhap = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        tpPassworld = new javax.swing.JPasswordField();
        lbMatKhau = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(229, 189, 240));
        kGradientPanel1.setkStartColor(new java.awt.Color(168, 168, 233));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        lbTitle.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("Đăng nhập");

        lbTenDangNhap.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbTenDangNhap.setForeground(new java.awt.Color(252, 244, 252));
        lbTenDangNhap.setText("Tên đăng nhập: ");

        txtTenDN.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N

        tpPassworld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpPassworldActionPerformed(evt);
            }
        });

        lbMatKhau.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbMatKhau.setForeground(new java.awt.Color(252, 244, 252));
        lbMatKhau.setText("Mật khẩu: ");

        btnDangNhap.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(72, 61, 139));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(72, 61, 139));
        btnHuy.setText("Hủy");
        btnHuy.setMaximumSize(new java.awt.Dimension(159, 41));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenDangNhap, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMatKhau, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenDN)
                            .addComponent(tpPassworld, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbTitle))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMatKhau)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(tpPassworld, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tpPassworldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpPassworldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpPassworldActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (this.batLoi()) {
            String name = "", passt = "", vaitroT = "";
            String pass = new String(tpPassworld.getPassword());
            String sql = "select * from NGUOIDUNG\n"
                    + "WHERE USENAME = ?";
            try {

                PreparedStatement pstm = cn.prepareStatement(sql);
                pstm.setString(1, txtTenDN.getText());
                ResultSet rs = pstm.executeQuery();
                while (rs.next()) {
                    name = rs.getString(1);
                    passt = rs.getString(2);
                    vaitroT = rs.getString(3);
                }
                if (name.length() == 0) {
                    JOptionPane.showMessageDialog(this, "Không tồn tại người dùng");
                    return;
                } else {
                    if (!pass.trim().equalsIgnoreCase(passt)) {
                        JOptionPane.showMessageDialog(this, "Sai mật khẩu mời đăng nhập lại");
                        return;
                    } else {
                        if (vaitroT.equals("1")) {
                            JOptionPane.showMessageDialog(this, "Bạn đăng nhập quyền quản trị");
                            vaitro = true;
                        } else {
                            JOptionPane.showMessageDialog(this, "Bạn là nhân viên");
                            vaitro = false;
                        }

                        QuanLiBanHangIphone ql = new QuanLiBanHangIphone(vaitro, name);
                        ql.setLocationRelativeTo(null);
                        ql.setVisible(true);
                        this.setVisible(false);
                    }
                }

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnHuy;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTenDangNhap;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPasswordField tpPassworld;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables

    public boolean batLoi() {
        boolean tdn = false, matkhau = false;
        if (txtTenDN.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn tên đăng nhập");
            tdn = false;
        } else {
            tdn = true;
        }
        if (tpPassworld.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập mật khẩu");
            matkhau = false;
        } else {
            matkhau = true;
        }
        if (tdn == true && matkhau == true) {
            return true;
        } else {
            return false;
        }
    }
}
