/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainMenu;

import com.sun.net.httpserver.Authenticator;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HungIT
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection cn;
    boolean vaitro;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        cbNhoMatKhau = new javax.swing.JCheckBox();
        btnHuy = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        lbMatKhau = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        lbTenDangNhap = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        tpPassworld = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(624, 428));

        kGradientPanel1.setkEndColor(new java.awt.Color(229, 189, 240));
        kGradientPanel1.setkStartColor(new java.awt.Color(168, 168, 233));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(624, 428));

        cbNhoMatKhau.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        cbNhoMatKhau.setForeground(new java.awt.Color(252, 244, 252));
        cbNhoMatKhau.setText("Nhớ mật khẩu ");
        cbNhoMatKhau.setIconTextGap(10);
        cbNhoMatKhau.setOpaque(false);

        btnHuy.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(72, 61, 139));
        btnHuy.setText("Hủy");
        btnHuy.setMaximumSize(new java.awt.Dimension(159, 41));

        btnDangNhap.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(72, 61, 139));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        lbMatKhau.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbMatKhau.setForeground(new java.awt.Color(252, 244, 252));
        lbMatKhau.setText("Mật khẩu: ");

        txtTenDN.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N

        lbTenDangNhap.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbTenDangNhap.setForeground(new java.awt.Color(252, 244, 252));
        lbTenDangNhap.setText("Tên đăng nhập: ");

        lbTitle.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("Đăng nhập");

        tpPassworld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpPassworldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenDangNhap)
                            .addComponent(lbMatKhau))
                        .addGap(37, 37, 37)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDN)
                            .addComponent(tpPassworld))
                        .addGap(17, 17, 17))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(cbNhoMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMatKhau)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(tpPassworld, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(33, 33, 33)
                .addComponent(cbNhoMatKhau)
                .addGap(34, 34, 34)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        try {
            String user = "sa", password = "123";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://ADMIN\\SQLEXPRESS:1433;databaseName=QLIPHONE";
            Connection cn = DriverManager.getConnection(url, user, password);
            String sql = "Select * from nguoidung where usename=? and password=?";

            PreparedStatement pts = cn.prepareStatement(sql);
            pts.setString(1, txtTenDN.getText());
            String passWord = new String(tpPassworld.getPassword());
            pts.setString(2, passWord);
            ResultSet rs = pts.executeQuery();

            while (rs.next()) {
               if(rs.getString(3).equals("1")){
                   vaitro=true;
               }
               else{
                   vaitro=false;
               }

            }
            rs.close();
            pts.close();

            if (vaitro == true) {
                JOptionPane.showMessageDialog(this,  "Bạn đã đăng nhập với vai trò quản trị viên");
                
            } else {
                //xử lý khi đăng nhập thành công                
                JOptionPane.showMessageDialog(this,  "Bạn đã đăng nhập với vai trò nhân viên");
//            
            }
            QuanLiBanHangIphone ql = new QuanLiBanHangIphone();
            ql.setVisible(true);
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi Login");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed
//    public boolean role(){
//    
//    }

    public boolean batLoi() {
        boolean tdn = false, matkhau = false;
        if (txtTenDN.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn tên đăng nhập");
            tdn = false;
        } else {
            tdn = true;
        }
        if (tpPassworld.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập mật khẩu");
            matkhau = false;
        } else {
            matkhau = true;
        }
        if (tdn == true && matkhau == true) {
            return true;
        } else {
            return false;
        }
    }
    private void tpPassworldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpPassworldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpPassworldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnHuy;
    private javax.swing.JCheckBox cbNhoMatKhau;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTenDangNhap;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPasswordField tpPassworld;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
